### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Prinzenrolle90** [anujdatar/onenote-desktop#10]
Hi. I have an Error during startup. 
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/somebody/snap/onenote-desktop/8/OneNote/config.json' at Object.chownSync (fs.js:1142:3) at Function.writeFileSync [as sync] (/snap/onenote-desktop/8/resources/app.asar/node_modules/write-file-automic/index.js:196:27) at ElectronStore.set store [as store] (/snap/onenote-desktop/8/resources/app.asar/node_modules/conf/index.js:277:19) at ElectronStore.set(/snap/onenote-desktop/8/resources/app.asar/node_modules/conf/index.js:152:14) at BrowserWindows.<anonymous>(/snaponenote-desktop/8/8resources/app.asar/src/main.js:54:10) at BrowseWindows.emit (events.js:194:13)

running on Manjaro. Everything is updated. 
I have the same error on after reinstalling with edge.

**Comment by slillon** [comment]
Hi, same error running on ubuntu 18

**Comment by MRJ-Bamford-King** [comment]
Same error, pls help!

**Comment by daviddecobros** [comment]
Hi, I found the same issue. Ubuntu 18.04.3 LTS. Gnome 3.28.2 SO x64 bits.
If you need more information... 
from console:
_Gtk-Message: 17:44:29.676: GtkDialog mapped without a transient parent. This is discouraged._

Thanks

**Comment by bladelei** [comment]
same error 
![image](https://user-images.githubusercontent.com/29811797/70885262-5920a300-2013-11ea-9ab0-47b2b4e29a52.png), pls help!

**Comment by hrenmrj** [comment]
Same here Ubuntu 18.04

**Comment by nik0811** [comment]
Temporary solution is to give 777 permission to snap folder in home directory.
`sudo chmod -R 777 snap/`

**Comment by Fitz13009** [comment]
Same from 19.10

**Comment by GhettoBurger996** [comment]
A temporary solution to this problem is to open up one note and once the error pops up simply minimize it and basically ignore it. Afterwards you'll notice that One Note just keeps attempting to load up, go to the taskbar (View -> Force Reload), and everything should work fine. 

Again only temporary solution as the error prompt window will have to stay open. But everything other then that works fine!

**Comment by Rullec** [comment]
Save error from 18.04, Thanks!

**Comment by osorioagustin** [comment]
Having the same issue for Ubuntu 20.04 LTS, any solution found?

**Comment by annagthb** [comment]
Hi I have the same issue on Ubuntu version 18.04.4 LTS. The temporary solution sometimes works, but sometimes the One Note window just does not load and the error still remains there. Any permanent fix would be appreciated. Thank you!

**Comment by yusufbarisk** [comment]
Heyy, any solutions yet? Any Ideas why it may be caused???

**Comment by darth-franky** [comment]
Hi, 
Is anyone working on this? Having the same issue on Ubuntu 20.04 LTS

**Comment by RoryGlenn** [comment]
Having the same problem

**Comment by ViktorYeah** [comment]
# 1
snap remove onenote-desktop
sudo apt update
sudo apt install snapd

# 2
RESTART SYSTEM !!!

from [](https://snapcraft.io/install/onenote-desktop/ubuntu)
> Either log out and back in again, or restart your system, to ensure snap’s paths are updated correctly.

# 3
sudo snap install onenote-desktop --beta

# 4
onenote-desktop

# 5
:)

**Comment by anujdatar** [comment]
I apologize for the massive delay in replying to the thread. I had fixed the error on my computer and moved on to other programs/projects since I initially published this package. I think i forgot to push my changes, before I changed my computer and lost some code.

And, I am not sure why I was unsubscribed from this repo's updates. I did not know so many people had the same errors, or that other people were even using this. An oversight on my part.

I have just published an updated version of the app, with Snap, Deb and AppImage files. I should have the snap package published  in a bit.

While I labelled the release as alpha pre-release, I have tested it on Ubuntu/Kubuntu 20.04 and 20.10. Everything should be running fine. I will bump it to a stable release soon, once my laptop is fixed and have spent some time on further testing.

Thanks for the patience.
