### ISSUE TITLE
Where Do I find OneNote after installation

### ISSUE THREAD

**Issue by webzest** [anujdatar/onenote-desktop#14]
Hi,
I installed OneNote from your Git Repository and started it.  It worked fine, but after I closed the app, I can't find it on my linux Mint system.  do I have to use the console and run the npm install and start every time?

**Comment by anujdatar** [comment]
Hi, I apologize for the delayed reply. I had automatically been unsubscribed from the repo, and I do not know why. I have published an update with a bunch of fixes now.

To answer your question:

How did you start the app? Did you clone the repo and run npm install / start? If yes, then you will need to cd into the folder and run `npm start` each time. But this is only appropriate for development. If you want to use it as a regular program, I would recommend using Deb, Snap, or AppImage packages. You will find the latest error free files in the releases section for this repo. And I should have a snap package published on Snapcraft soon. So you can use `snap install onenote-desktop` once I have that done. I will post an update in the main readme.

Thank you for your patience.

**Comment by anujdatar** [comment]
Closing, since this is not really an issue.
Also, just FYI,
1. If you clone the repo and use npm start - the OneNote-desktop application stays in that same location.
2. If you install the `.deb` package, installation location is in `/opt/onenote-desktop` I believe.
3. If you install the `snap` package, installation goes to `/snap/onenote-desktop` and local/user configuration files are stored in `/user/<username>/snap/onenote-desktop`
4. If you use the `AppImage`, then the application launches from where ever the `.AppImage` file is stored. and you can launch the app by double clicking on the file. Unfortunately I don't have AppImage icon/shortcut scripts set up yet, so you will need to create those yourself if you want them to show up in your "Start Menu/App Drawer"

Let me know if you have further questions.
