### ISSUE TITLE
Cannot return from browser after opening hyperlink

### ISSUE THREAD

**Issue by bwirt** [anujdatar/onenote-desktop#21]
Clicking on a hyperlink now opens a browser inside the OneNote application.  Once the link opens, there is no way to go back.  Even closing the application and relaunching will return to the same browser page instead of the notebook.

**Comment by anujdatar** [comment]
Hi, sorry about that. This bug is actually due to an oversight on my part. I am working on a feature concurrently that should fix this. In the meantime, I have a temporary fix for you:

Are you using the Deb package or Snap package?

If you are using .deb:
1. Close the app
2. Go to `~/.config/onenote-desktop` or `~/.config/OneNote`
3. Delete the `config.json` file
4. Restart the app. It should go back to the OneNote notebook selection screen

If you are using .snap or onenote-desktop from snapcraft
1. Close the app
2. Go to `~/snap/onenote-desktop/current/.config/OneNote/`
3. Delete the `config.json` file
4. Restart the app. It should go back to the OneNote notebook selection screen

This should work for now. I will push an update to fix this issue asap. Sorry for the inconvenience.

**Comment by FGobz7** [comment]
Just to add info regarding this bug. In my case, I use Manjaro Gnome and I installed the software from Snap.
I found out the config.json file in this location: `home/<user>/snap/onenote-desktop/13/.config/OneNote`

**Comment by anujdatar** [comment]
> I found out the config.json file in this location: `home/<user>/snap/onenote-desktop/13/.config/OneNote`

Thanks. Yes, the number usually depends on the installation, version, etc. 

> 2. Go to `~/snap/onenote-desktop/current/.config/OneNote/`

Whereas, the `current` folder is generally a symlink to the latest installed/updated version. So that's the way to go if you want to make sure you are deleting the latest config file.

I am working on an update for the app presently. Should be live in some time.

**Comment by anujdatar** [comment]
should be fixed in v2.0.0.

1. There is a return to homepage button in the app menubar now.
2. There are app reset options too if you run into more issues
