### ISSUE TITLE
How to locate OneNote app files Ubuntu (snap)/ App opens up to a white screen

### ISSUE THREAD

**Issue by gaurishdotkdm** [anujdatar/onenote-desktop#25]
Hi Anuj,

I installed "OneNote Desktop Client for Linux" using snapd.

$ sudo snap install onenote-desktop

After a 2-3 weeks of use, now the application is unable to open successfully and only shows white empty screen.

1. Is there a way to recover my notes on the machine? I can't recollect my outlook login info. So I cannot access onenote over web using outlook account.
2. Else, is there a workaround to get this working?
3. Else, can I transfer any files to another Ubuntu machine and read my notes?

OS: Ubuntu 20.04.3 LTS
GNOME Version: 3.36.8

Thanks for your time!

**Comment by anujdatar** [comment]
Hi, this should be an easy fix actually. I am guessing something may have caused the last visited link to be stored incorrectly. Issue #21 is kinda similar, and the fix is the same. Here are the relevant steps to correct this.

> If you are using .snap or onenote-desktop from snapcraft
> 1. Close the app
> 2. Go to `~/snap/onenote-desktop/current/.config/OneNote/`
> 3. Delete the `config.json` file
> 4. Restart the app. It should go back to the OneNote notebook selection screen

Since you do not remember your login info, **do not delete** the entire `~/snap/onenote-desktop/current/.config/OneNote/`. If you do that the app will reset and you will not be able to log in again. As far as I know, these notes are not stored locally in human readable formats (but i may be wrong). You need to be connected to OneNote web in order to access the notes.

I was working on an update that makes such resets easier, back then. It should be in the alpha channel, but it was a buggy fix, so it never made it to a stable release. Recently, I have been more focused on a `python+gtk` alternative to `Electron`. Which in my experience has been less resource hungry. In hindsight, i probably should fix my existing release before the full overhaul..

Anyway, let me know if this works for you, or if you have trouble finding the `.config/OneNote` folder

**Comment by gaurishdotkdm** [comment]
Excellent!

Followed 4 steps mentioned above. I could get to the notebook selection page safely.

**Comment by anujdatar** [comment]
Great, glad I could help
