### ISSUE TITLE
Onenote not working

### ISSUE THREAD

**Issue by Dyansi** [anujdatar/onenote-desktop#40]
Hello, 
Thanks for the service you provide.

I get this error when I try using onenote:

_**Sorry, we can't get your notebooks right now. Please try again later.
Reference number: fef15dc4-29c0-4d29-aa96-f53dd7856dfb**_

What should I do?

**Comment by anujdatar** [comment]
Hey, I sorry about the late reply, been down with covid this last week.

I think this might have been an issue with OneNote servers maybe? Do you still see this issue? Let me know.

Thanks,
Anuj

**Comment by anujdatar** [comment]
Oh, okay.

Have you tried an app reset? Check the `App Reset` options in the help menu? Or you can check how to manually reset the app [here](https://github.com/anujdatar/onenote-desktop#manually-resetting-the-app).

Are you using the `snap` package?

**Comment by Dyansi** [comment]
Yes, I'm using the snap package and I tried the app reset as well but same
issue.
As you said, the problem might be from the server. The same thing happens
when tried from a browser.
Thanks.

**Comment by anujdatar** [comment]
Hmm.. Actually I am not sure about the servers being the problem. Because I was able to log in and get my notes this morning. I tested the Windows native app, Chrome on Linux, and this app. I was able to access everything.

Maybe try uninstalling and reinstalling the application. Clearing out your browser's cache and local storage for the website.

**Comment by Dyansi** [comment]
Interesting. I will try that.
Thanks

**Comment by anujdatar** [comment]
closing stale issue because of lack of information from user
