### ISSUE TITLE
When pasting code from vs code to OneNote, the formatting will be all messed up and code becomes unreadable

### ISSUE THREAD

**Issue by yuchenOutlook** [anujdatar/onenote-desktop#42]
When pasting code from vs code to OneNote, the formatting will be all messed  up and code becomes unreadable

**Comment by anujdatar** [comment]
Hi,

I am guessig you are using a dark theme inside VSCode? I just tried a couple of things, using dark mode in VS Code.
1. Pasting code from VSCode into OneNote Desktop app on Windows.
2. Pasting code into the OneNote WebApp in a browser on Ubuntu.
3. Pasting code into my OneNote Snap package on Ubuntu.

Everything works fine on the Windows native app. But on Linux, in both Chrome and my Snap package, a dark theme causes all the text to have a dark highlight and makes some parts unreadable.

This seems to be a Microsoft issue, I unfortunately can't really control how the web app works. I just serve the app inside a container.

I have a suggestion though. If you need a notes app for coding, OneNote is probably not the best tool. You could try a Markdown based notes app. They support better code annotation, generally rely on local storage so switching between notebooks and pages is quicker. And once you get used to markdown, things will just go smoother.

I created this OneNote app a few years ago when I was transitioning from Windows to Linux. I rarely use it anymore, just update it ever so often. I personally use:
1. Joplin, which is open source. Supports Vim and Emacs key bindings. Uses local storage for notes, but you can set up sync using Dropbox, OneDrive, NextCloud etc. No plugin for drawing like OneNote unfortunately.

2. Obsidian.md. It is closed source, but free to use and has a lot of plugin options. Has an interesting graph-view thing (which i don't use personally). It also supports Vim bindings. Has a good plugin for drawing (Excelidraw). Sync could be an issue since the integrated sync is paid, but there is a plugin for external sync. Or you can manually set it up using dropbox or NextCloud or something.

They both come with apps for Windows, Mac, Linux, iOS and Android.

Boost Notes used to have a good local app, but I think they ended support for that and have transitioned to a cloud based service.
