### ISSUE TITLE
App hijacks the F1 key

### ISSUE THREAD

**Issue by paveldvorak5** [anujdatar/onenote-desktop#62]
When I press the F1 key in another app, the about dialog appears.

OneNote-Desktop v2.2.1 @ Debian Bookworm

Thanks

**Comment by anujdatar** [comment]
Hi, thanks for letting me know. I'll test it out today and issue a patch asap.

Anuj

**Comment by anujdatar** [comment]
Okay, so that was a weird one. F1 worked just fine when using other apps. For me the issue only popped up when I was using Chrome. That's the only time I saw OneNote Desktop hijack the F1 key. Makes me think this might be a problem when using other Chromium or Electron based apps too.

Anyway, I have disabled the F1 accelerator/shortcut in the latest release. So you shouldn't have that problem anymore. Release 2.2.2 should be live. If you are using the snap package from snapstore, give it a few hours to propogate to all users. Otherwise feel free to grab the latest release from the release page.
